version: '3'

services:
  nobl:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./examples.nobl:/app/examples.nobl
      - ./test.nobl:/app/test.nobl
